import { faLock, faLeaf, faHouse, faUser, faFileAlt, faTimes, faArrowLeft, faKey, faFile, faCircleUser, faMountainSun, faCircleChevronLeft, faSpa, faMapLocationDot, faCalendarPlus, faSackDollar, faSeedling, faListCheck, faTractor, faFileContract, faGear, faUserGroup, faRightFromBracket, faTrashCan, faSquareCheck, faPenToSquare, faCircleDollarToSlot, faMobileAndroid, faUserPlus, faPieChart, faDownload, faQuestion, faCopyright, faEnvelope } from '@fortawesome/free-solid-svg-icons';
import { faGithub, faGooglePlay, faFigma } from '@fortawesome/free-brands-svg-icons';

const iconos = {
    /* Iconos */
    iconoUsuario: faUser,
    iconoCandado: faLock,
    iconoDocumento: faFileAlt,
    iconoCultivo: faSeedling,
    iconoTractor: faTractor,
    iconoX: faTimes,
    iconoFlechaDerecha: faCircleChevronLeft,
    iconoLlave: faKey,
    iconoDocumentoDos: faFile,
    iconoPerfilUsuario: faCircleUser,
    iconoFinca: faMountainSun,
    iconoActividad: faListCheck,
    iconoReporte: faFileContract,
    iconoSoporte: faGear,
    iconoUsuarios: faUserGroup,
    iconoSalir: faRightFromBracket,
    iconoInicio: faHouse,
    iconoLote: faLeaf,
    iconoProduccion: faSackDollar,
    iconoProgramacion: faCalendarPlus,
    iconoMapa: faMapLocationDot,
    iconoVariedad: faSpa,
    iconoVolver: faArrowLeft,
    iconoDesactivar: faTrashCan,
    iconoActivar: faSquareCheck,
    iconoEditar: faPenToSquare,
    iconoAgregarUsuario: faUserPlus,
    iconoGrafica: faPieChart,
    iconoDescargar: faDownload,
    iconoPregunta: faQuestion,
    iconoCostos: faCircleDollarToSlot,
    iconoTelefono: faMobileAndroid,
    iconoCopyRight: faCopyright,
    iconoGitHub: faGithub,
    iconoGmail: faEnvelope,
    iconoFigma: faFigma,
    iconoApp: faGooglePlay,
}
export default iconos;